import { generateText, streamText, wrapLanguageModel, stepCountIs, extractReasoningMiddleware } from "ai";
import { devToolsMiddleware } from "@ai-sdk/devtools";
import axios from "axios";
import { transform } from "sucrase";
import u from "@/utils";
import { getXiaoyuExecutionContext, runWithXiaoyuExecutionContext } from "@/xiaoyu/executionContext";
import { getXiaoyuAccessToken } from "@/xiaoyu/computeCenterClient";
type AiType="scriptAgent"|"productionAgent"|"universalAi"|"scriptAgent:decisionAgent"|"scriptAgent:supervisionAgent"|"scriptAgent:storySkeletonAgent"|"scriptAgent:adaptationStrategyAgent"|"scriptAgent:scriptAgent"|"productionAgent:decisionAgent"|"productionAgent:supervisionAgent"|"productionAgent:deriveAssetsAgent"|"productionAgent:generateAssetsAgent"|"productionAgent:directorPlanAgent"|"productionAgent:storyboardGenAgent"|"productionAgent:storyboardPanelAgent"|"productionAgent:storyboardTableAgent";
type FnName="textRequest"|"imageRequest"|"videoRequest"|"ttsRequest";
const AiTypeValues:AiType[]=["scriptAgent","productionAgent","universalAi","scriptAgent:decisionAgent","scriptAgent:supervisionAgent","scriptAgent:storySkeletonAgent","scriptAgent:adaptationStrategyAgent","scriptAgent:scriptAgent","productionAgent:decisionAgent","productionAgent:supervisionAgent","productionAgent:deriveAssetsAgent","productionAgent:generateAssetsAgent","productionAgent:directorPlanAgent","productionAgent:storyboardGenAgent","productionAgent:storyboardPanelAgent","productionAgent:storyboardTableAgent","universalAi"];
async function resolveModelName(value:AiType|`${string}:${string}`):Promise<`${string}:${string}`>{if(AiTypeValues.includes(value as AiType)){const mode=await u.db("o_setting").where("key","agentUseMode").first();if(mode?.value==="1"){const row=await u.db("o_agentDeploy").where("key",value).first();if(!row?.modelName)throw new Error(`高级配置模式下，未找到对应的模型配置 ${value}`);return row.modelName;}if(mode?.value==="0"){const[main]=String(value).split(/:(.+)/);const row=await u.db("o_agentDeploy").where("key",main).first();if(!row?.modelName)throw new Error(`简易配置模式下，未找到部署配置 ${value}`);return row.modelName;}const row=await u.db("o_agentDeploy").where("key",value).first();if(row?.modelName)return row.modelName;const[main]=String(value).split(/:(.+)/);const fallback=await u.db("o_agentDeploy").where("key",main).first();if(!fallback?.modelName)throw new Error(`未找到部署配置 ${value}；请在 设置 → Agent 配置 中选择文本模型`);return fallback.modelName;}return value as `${string}:${string}`;}
async function getModelConfig(value:AiType|`${string}:${string}`){if(AiTypeValues.includes(value as AiType)){const mode=await u.db("o_setting").where("key","agentUseMode").first();if(mode?.value==="1"){const row=await u.db("o_agentDeploy").where("key",value).first();if(!row?.modelName)throw new Error(`高级配置模式下，未找到对应的模型配置 ${value}`);return row;}if(mode?.value==="0"){const[main]=String(value).split(/:(.+)/);const row=await u.db("o_agentDeploy").where("key",main).first();if(!row?.modelName)throw new Error(`简易配置模式下，未找到部署配置 ${value}`);return row;}const row=await u.db("o_agentDeploy").where("key",value).first();if(row?.modelName)return row;const[main]=String(value).split(/:(.+)/);const fallback=await u.db("o_agentDeploy").where("key",main).first();if(!fallback?.modelName)throw new Error(`未找到部署配置 ${value}；请在 设置 → Agent 配置 中选择文本模型`);return fallback;}return null;}
async function getVendorTemplateFn(fnName:"textRequest",modelName:`${string}:${string}`):Promise<(think?:boolean,thinkLevel?:0|1|2|3)=>any>;
async function getVendorTemplateFn(fnName:Exclude<FnName,"textRequest">,modelName:`${string}:${string}`):Promise<(input:any)=>any>;
async function getVendorTemplateFn(fnName:FnName,modelName:`${string}:${string}`):Promise<any>{const[id,name]=modelName.split(/:(.+)/);const vendorConfigData=await u.db("o_vendorConfig").where("id",id).first();if(!vendorConfigData)throw new Error(`未找到供应商配置 id=${id}`);const modelList=await u.vendor.getModelList(id);const selectedModel=modelList.find((i:any)=>i.modelName==name);if(!selectedModel)throw new Error(`未找到模型 ${name} id=${id}`);const code=u.vendor.getCode(id);const jsCode=transform(code,{transforms:["typescript"]}).code;const running=u.vm(jsCode);if(running.vendor){Object.assign(running.vendor.inputValues,JSON.parse(vendorConfigData.inputValues??"{}"));if(id==="xiaoyu_compute_center"){const context=getXiaoyuExecutionContext();Object.assign(running.vendor.inputValues,{apiKey:await getXiaoyuAccessToken(),productId:"xiaoyu-drama",qualityMode:context?.qualityMode||"",policyVersion:context?.policyVersion||"",projectRef:context?.projectRef||"",runId:context?.runId||"",nodeKey:context?.nodeKey||"",stageRef:context?.stageRef||"",entityType:context?.entityType||"",entityId:context?.entityId===undefined?"":String(context.entityId),idempotencyScope:context?.idempotencyScope||""});}running.vendor.models=modelList;}const fn=running[fnName];if(!fn)throw new Error(`未找到供应商配置中的函数 ${fnName} id=${id}`);if(fnName==="textRequest")return(think?:boolean,thinkLevel:0|1|2|3=0)=>fn(selectedModel,think??!!selectedModel.think,thinkLevel);return<T>(input:T)=>fn(input,selectedModel);}
async function withTaskRecord<T>(modelKey:AiType|`${string}:${string}`,taskClass:string,describe:string,relatedObjects:string,projectId:number,fn:(modelName:`${string}:${string}`,think:Boolean,thinkLevel:0|1|2|3)=>Promise<T>):Promise<T>{const modelName=await resolveModelName(modelKey);const[,model]=modelName.split(/:(.+)/);const taskRecord=await u.task(projectId,taskClass,model,{describe,content:relatedObjects});try{const project=await u.db("o_project").where("id",projectId).first();const current=getXiaoyuExecutionContext();const result=current?await fn(modelName,false,0):await runWithXiaoyuExecutionContext({requestId:`xyreq_${u.uuid()}`,projectId,projectRef:String(projectId),qualityMode:project?.qualityMode as any,policyVersion:project?.computePresetVersion||undefined,stageRef:taskClass,entityType:"task",entityId:relatedObjects,idempotencyScope:`${projectId}:${taskClass}:${relatedObjects}`},()=>fn(modelName,false,0));taskRecord(1);return result;}catch(e){taskRecord(-1,u.error(e).message);throw new Error(u.error(e).message);}}
async function urlToBase64(url:string,retries=3,delay=1000):Promise<string>{for(let attempt=1;attempt<=retries;attempt++){try{const res=await axios.get(url,{responseType:"arraybuffer"});return Buffer.from(res.data).toString("base64");}catch(e){if(attempt===retries)throw e;await new Promise(r=>setTimeout(r,delay*attempt));}}throw new Error("urlToBase64 failed");}
class AiText{constructor(private AiType:AiType|`${string}:${string}`,private think?:boolean,private thinkLevel:0|1|2|3=0){}private async resolveModel(middleware?:any|any[]){const sw=await u.db("o_setting").where("key","switchAiDevTool").first();const modelName=await resolveModelName(this.AiType);const sdkFn=await getVendorTemplateFn("textRequest",modelName);const baseModel=await sdkFn(this.think,this.thinkLevel);const mws=[...(sw?.value==="1"?[devToolsMiddleware()]:[]),...(middleware?(Array.isArray(middleware)?middleware:[middleware]):[])];return mws.length?wrapLanguageModel({model:baseModel,middleware:mws.length===1?mws[0]:mws}):baseModel;}async invoke(input:Omit<Parameters<typeof generateText>[0],"model">){const config=await getModelConfig(this.AiType);return generateText({...input,...(input.tools&&{stopWhen:stepCountIs(Object.keys(input.tools).length*50)}),model:await this.resolveModel(),...(config?.temperature&&{temperature:config.temperature}),maxOutputTokens:config?.maxOutputTokens&&config.maxOutputTokens>0?config.maxOutputTokens:32768} as any);}async stream(input:Omit<Parameters<typeof streamText>[0],"model">){const config=await getModelConfig(this.AiType);return streamText({...input,...(input.tools&&{stopWhen:stepCountIs(Object.keys(input.tools).length*50)}),model:await this.resolveModel(extractReasoningMiddleware({tagName:"reasoning_content",separator:"\n"})),...(config?.temperature&&{temperature:config.temperature}),maxOutputTokens:config?.maxOutputTokens&&config.maxOutputTokens>0?config.maxOutputTokens:32768} as any);}}
function referenceList2imageBase642(id:string,input:any){const version=u.vendor.getVendor(id).version;if(!version||isNaN(parseFloat(version))||parseFloat(version)<2.0){if(Array.isArray(input.referenceList))input.imageBase64=input.referenceList.map((item:any)=>item?.base64).filter(Boolean);}return input;}
export type ReferenceList={type:"image";base64:string}|{type:"audio";base64:string}|{type:"video";base64:string};
interface ImageConfig{prompt:string;referenceList?:Extract<ReferenceList,{type:"image"}>[];size:"1K"|"2K"|"4K";aspectRatio:`${number}:${number}`;}interface TaskRecord{taskClass:string;describe:string;relatedObjects:string;projectId:number;}
class AiImage{private result="";constructor(private key:`${string}:${string}`){}async run(input:ImageConfig,taskRecord?:TaskRecord){const modelName=await resolveModelName(this.key);const exec=async(mn:`${string}:${string}`)=>{const fn=await getVendorTemplateFn("imageRequest",mn);referenceList2imageBase642(mn.split(/:(.+)/)[0],input);this.result=await fn(input);if(typeof this.result!=="string"||!this.result.trim())throw new Error("图片供应商未返回图片数据");if(this.result.startsWith("http"))this.result=await urlToBase64(this.result);return this;};if(taskRecord)await withTaskRecord(this.key,taskRecord.taskClass,taskRecord.describe,taskRecord.relatedObjects,taskRecord.projectId,exec);else await exec(modelName);return this;}async save(path:string){await u.oss.writeFile(path,this.result);return this;}}
type VideoMode="singleImage"|"startEndRequired"|"endFrameOptional"|"startFrameOptional"|"text"|(`videoReference:${number}`|`imageReference:${number}`|`audioReference:${number}`)[];interface VideoConfig{duration:number;resolution:string;aspectRatio:"16:9"|"9:16";prompt:string;referenceList?:ReferenceList[];audio?:boolean;mode:VideoMode[];}
class AiVideo{private result="";constructor(private key:`${string}:${string}`){}async run(input:VideoConfig,taskRecord?:TaskRecord){const modelName=await resolveModelName(this.key);const exec=async(mn:`${string}:${string}`)=>{const fn=await getVendorTemplateFn("videoRequest",mn);referenceList2imageBase642(mn.split(/:(.+)/)[0],input);this.result=await fn(input);if(typeof this.result!=="string"||!this.result.trim())throw new Error("视频供应商未返回视频数据");if(this.result.startsWith("http"))this.result=await urlToBase64(this.result);};if(taskRecord)await withTaskRecord(this.key,taskRecord.taskClass,taskRecord.describe,taskRecord.relatedObjects,taskRecord.projectId,exec);else await exec(modelName);return this;}async save(path:string){await u.oss.writeFile(path,this.result);return this;}}
class AiAudio{private result="";constructor(private key:`${string}:${string}`){}async run(input:VideoConfig,taskRecord?:TaskRecord){const modelName=await resolveModelName(this.key);const exec=async(mn:`${string}:${string}`)=>{const fn=await getVendorTemplateFn("ttsRequest",mn);referenceList2imageBase642(mn.split(/:(.+)/)[0],input);this.result=await fn(input);if(this.result.startsWith("http"))this.result=await urlToBase64(this.result);return this;};if(taskRecord)return withTaskRecord(this.key,taskRecord.taskClass,taskRecord.describe,taskRecord.relatedObjects,taskRecord.projectId,exec);return exec(modelName);}async save(path:string){await u.oss.writeFile(path,this.result);return this;}}
export default{Text:(t:AiType|`${string}:${string}`,think?:boolean,l?:0|1|2|3)=>new AiText(t,think,l),Image:(k:`${string}:${string}`)=>new AiImage(k),Video:(k:`${string}:${string}`)=>new AiVideo(k),Audio:(k:`${string}:${string}`)=>new AiAudio(k)};
